# Generated by Django 5.0.14 on 2026-07-15 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('preferred_language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English'), ('sheng', 'Sheng')], default='sw', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
