# Generated by Django 5.0.14 on 2026-07-15 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='traders.trader')),
            ],
        ),
    ]
