# Generated by Django 5.0.14 on 2026-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='password_hash',
            field=models.CharField(default='default_hash', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trader',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
