# Generated by Django 5.0.14 on 2026-07-15 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('PAYOUT', 'Payout'), ('PAYMENT_REQUEST', 'Payment Request')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counterparty_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payhero_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_voice_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='traders.trader')),
            ],
        ),
    ]
