# Generated by Django 5.0.14 on 2026-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('AWAITING_CONFIRMATION', 'Awaiting Confirmation')], default='PENDING', max_length=30),
        ),
    ]
