# Generated by Django 5.0.14 on 2026-07-15 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommandLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcribed_text', models.TextField()),
                ('parsed_intent', models.JSONField()),
                ('action_taken', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_logs', to='traders.trader')),
            ],
        ),
    ]
