# Generated by Django 5.0.14 on 2026-07-15 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('SALE', 'Sale'), ('EXPENSE', 'Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_voice_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='traders.trader')),
            ],
        ),
    ]
